/**
 * Materializa variáveis públicas do frontend para o bundle (dev e produção).
 *
 * Fontes (prioridade):
 *   1. Variáveis de ambiente do processo (CI/CD, Docker, Vercel, Railway…)
 *   2. Arquivo .env na raiz do monorepo (desenvolvimento local)
 *
 * Gera apenas src/lib/env.generated.ts — sem .env.local.
 * Em produção, defina NEXT_PUBLIC_* no painel do host ou no Dockerfile antes do build.
 */
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const frontendRoot = path.resolve(__dirname, '..')
const monorepoRoot = path.resolve(frontendRoot, '..')
const sourceEnv = path.join(monorepoRoot, '.env')
const targetGenerated = path.join(frontendRoot, 'src', 'lib', 'env.generated.ts')

function parseEnvFile(filePath) {
  const vars = {}
  const lines = fs.readFileSync(filePath, 'utf8').split(/\r?\n/)

  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue

    const eq = trimmed.indexOf('=')
    if (eq === -1) continue

    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }

    vars[key] = value
  }

  return vars
}

function pick(fileVars, publicKey, fallbackKey) {
  return (
    process.env[publicKey] ||
    fileVars[publicKey] ||
    (fallbackKey ? process.env[fallbackKey] || fileVars[fallbackKey] : '') ||
    ''
  )
}

function escapeTsString(value) {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}

const fileVars = fs.existsSync(sourceEnv) ? parseEnvFile(sourceEnv) : {}
const hasFile = fs.existsSync(sourceEnv)
const hasProcess =
  Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL) &&
  Boolean(process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY)

const supabaseUrl = pick(fileVars, 'NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_URL')
const supabaseAnonKey = pick(fileVars, 'NEXT_PUBLIC_SUPABASE_ANON_KEY', 'SUPABASE_ANON_KEY')
const apiUrl =
  pick(fileVars, 'NEXT_PUBLIC_API_URL') || 'http://localhost:8000/api/v1'

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('[sync-env] Missing Supabase configuration.')
  if (!hasFile && !hasProcess) {
    console.error('  Local: create .env at the monorepo root (see .env.example).')
    console.error('  Production: set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY before npm run build.')
  } else {
    console.error('  Required: NEXT_PUBLIC_SUPABASE_URL (or SUPABASE_URL) and NEXT_PUBLIC_SUPABASE_ANON_KEY (or SUPABASE_ANON_KEY).')
  }
  process.exit(1)
}

const sourceLabel = hasProcess
  ? 'process environment'
  : hasFile
    ? sourceEnv.replace(/\\/g, '/')
    : 'unknown'

const generatedTs = `// Auto-generated by scripts/sync-env.mjs — do not edit.
// Source: ${sourceLabel}

export const NEXT_PUBLIC_SUPABASE_URL = '${escapeTsString(supabaseUrl)}'
export const NEXT_PUBLIC_SUPABASE_ANON_KEY = '${escapeTsString(supabaseAnonKey)}'
export const NEXT_PUBLIC_API_URL = '${escapeTsString(apiUrl)}'
`

fs.writeFileSync(targetGenerated, generatedTs, 'utf8')
console.log(`[sync-env] Wrote ${targetGenerated}`)
