-- AMRAD: Row Level Security (RLS) Setup
-- SUPERSEDED BY: migrations/fix_rls_security_hardening.sql
-- Run that file in Supabase SQL Editor for the canonical security configuration.
--
-- Summary of the hardened model:
-- 1. Helper functions use auth_id = auth.uid() (not researchers.id)
-- 2. Trigger blocks user_type/status escalation on researchers
-- 3. No INSERT policy on application_logs (backend service_role only)
-- 4. REVOKE ALL on public tables from anon + authenticated
-- 5. All data access goes through FastAPI + service_role key
